apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-0vnn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-0vnn
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-0vnn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-0vnn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-0vnn
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lypi-tenant/rhtap-demo-app/hacbs-test-project-0vnn@sha256:c8f7518817b37f7a616af03e1aece23a9f85e71cddaa3b4b226e6358a5547bbd
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
