apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-0vnn
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lypi-tenant/rhtap-demo-app/hacbs-test-project-0vnn@sha256:c8f7518817b37f7a616af03e1aece23a9f85e71cddaa3b4b226e6358a5547bbd
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
