apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-0vnn
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lypi-tenant/rhtap-demo-app/hacbs-test-project-0vnn@sha256:29b11abbfc33088edf19319048e284d08e06d67e9febaec3d2ed8b40d2fce507
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
